# Generated by Django 4.1 on 2024-05-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='now',
        ),
    ]
